POST http://localhost:3000/gogpt
Content-Type: application/json

{
  "message": "(PT-br) Separating the development and production environment in Golang? In short text"
}

###
POST http://localhost:3000/gogpt
Content-Type: application/json

{
  "message": "qual é a melhor IOS ou Android"
}